version: '3.4'

# this docker configuation is the run flavor (static)

services:
  backend:
    image: ${DOCKER_USERNAME}/deces-backend:${APP_VERSION}
    container_name: deces-backend
    build:
      context: ${BACKEND}
      target: ${EXEC_ENV}
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
        app_path: /${APP}
        app_name: ${APP}
        app_ver: ${APP_VERSION}
        port: ${BACKEND_PORT}
        NPM_FIX: ${NPM_FIX}
        NPM_LATEST: ${NPM_LATEST}
        NPM_VERBOSE: ${NPM_VERBOSE}
    environment:
      - NODE_ENV=${EXEC_ENV}
      - BACKEND_PORT=${BACKEND_PORT}
      - APP=${APP}
      - APP_VERSION=${APP_VERSION}
      - BACKEND_PROXY_PATH=${BACKEND_PROXY_PATH}
      - BACKEND_CONCURRENCY=${BACKEND_CONCURRENCY}
      - API_URL=${API_URL}
      - API_SSL=${API_SSL}
      - API_EMAIL=${API_EMAIL}
      - ES_URL=${ES_HOST}:${ES_PORT}
      - ES_INDEX=${ES_INDEX}
  redis:
    image: redis:alpine
    container_name: ${APP}-redis
    volumes:
      - ${REDIS_DATA}:/data


networks:
  default:
    external:
      name: ${DC_NETWORK}
