version: '3.4'

services:
  backend:
    image: ${APP}-backend-${EXEC_ENV}:${APP_VERSION}
    build:
      context: ${BACKEND}
      target: ${EXEC_ENV}
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
        app_path: /${APP}
        app_name: ${APP}
        app_ver: ${APP_VERSION}
        port: ${BACKEND_PORT}
        NPM_FIX: ${NPM_FIX}
        NPM_LATEST: ${NPM_LATEST}
        NPM_VERBOSE: ${NPM_VERBOSE}
    container_name: ${APP}-backend-${EXEC_ENV}
    environment:
      - NODE_ENV=${EXEC_ENV}
      - BACKEND_PORT=${BACKEND_PORT}
      - APP=${APP}
      - APP_VERSION=${APP_VERSION}
      - ES_URL=${ES_HOST}:${ES_PORT}
      - ES_INDEX=${ES_INDEX}
    volumes:
      - ${BACKEND}/src:/${APP}/src/
      - ${BACKEND}/dist:/${APP}/dist/
      - /${APP}/node_modules
    ports:
      - 8080:${BACKEND_PORT}

networks:
  default:
    external:
      name: ${DC_NETWORK}
