name: Docker image build CI

on: [push]

jobs:
  build:
    name: Docker image build CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        env:
          BACKEND_HOSTNAME: deces.matchid.io
      - name: Build the docker image
        run: make backend-build-all
      - name: Make deploy local
        run: make deploy-local
        env:
          FILES_TO_PROCESS: deces-1970.txt.gz
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
      - name: Push the docker image
        if: steps.extract_branch.outputs.branch == 'master'
        run: make docker-push
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
