name: Docker image build CI

on: [push]

jobs:
  build:
    name: 🐳 Docker image build CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: 🐋 Build the master docker image
        run: make backend-build-all
        env:
          NPM_VERBOSE: ""
      - name: 👷 Make deploy local
        run: make deploy-local
        env:
          FILES_TO_PROCESS: deces-2020-m01.txt.gz
          STORAGE_ACCESS_KEY: ${{ secrets.aws_access_key_id }}
          STORAGE_SECRET_KEY: ${{ secrets.aws_secret_access_key }}
      - name: 🚀 Push the docker image
        if: steps.extract_branch.outputs.branch == 'master' || steps.extract_branch.outputs.branch == 'dev'
        run: make docker-push GIT_BRANCH="$GIT_BRANCH"
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  bulk:
    name: Test bulk mode
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the dev docker image
        run: make backend-build-all
      - name: Make deploy local
        run: make config elasticsearch-storage-pull elasticsearch-restore elasticsearch docker-check up backup-dir-clean backend-test-bulk
        env:
          FILES_TO_PROCESS: deaths.txt.gz
          STORAGE_ACCESS_KEY: ${{ secrets.aws_access_key_id }}
          STORAGE_SECRET_KEY: ${{ secrets.aws_secret_access_key }}
