name: Test backend

on: [push]

jobs:
  build:
    name: Test backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the docker image
        run: make backend-build-all
      - name: Make deploy local
        run: make deploy-local
        env:
          FILES_TO_PROCESS: deces-1970.txt.gz
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
